#page title
page_title                                : Sage Wallet                               # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://testflight.apple.com/join/BmUdFXpP # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

license                                   : https://raw.githubusercontent.com/xch-dev/sage/refs/heads/main/LICENSE  # Enter license type (e.g. MIT, GPL, proprietary).
download                                  : https://github.com/xch-dev/sage/releases  # Enter a link to download page

app_icon                                  : assets/sage-logo.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Sage Wallet                               # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The sagest wallet for the Chia blockchain.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Rigidity                                
your_link                                 :                      
your_city                                 :                                 
email_address                             :  
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : Rigidity16
github_username                           : xch-dev
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Fast and Secure
    description                           : A high-performance light wallet that can connect directly to peers on the Chia network. Can optionally connect to a trusted full node.
    fontawesome_icon_name                 : bolt
    
  - title                                 : WalletConnect
    description                           : Supports WalletConnect, allowing you to connect to DApps and DeFi services.
    fontawesome_icon_name                 : link

  - title                                 : Cross Platform
    description                           : Available on all desktop and mobile platforms, including Windows, macOS, Linux, iOS and Android.
    fontawesome_icon_name                 : mobile

  - title                                 : Offer Files
    description                           : Supports the creation, viewing, and acceptance of Chia Offer files.
    fontawesome_icon_name                 : sync

  - title                                 : NFT Support
    description                           : Supports the Chia NFT standard. Includes NFT management and DID transfers.
    fontawesome_icon_name                 : images
  
  - title                                 : CAT Support
    description                           : Supports the Chia Asset Token standard. Includes automatic CAT detection.
    fontawesome_icon_name                 : cat

  - title                                 : Minting
    description                           : Mint new tokens on the Chia blockchain. Includes support for NFTs and CATs.
    fontawesome_icon_name                 : star

  - title                                 : DID Profiles
    description                           : Create and manage Decentralized Identifiers (DIDs) profiles and attach to NFTs.
    fontawesome_icon_name                 : id-card
  
  - title                                 : Coin Management
    description                           : Supports advanced coin management features, including coin splitting and merging.
    fontawesome_icon_name                 : coins



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
